// let sum = (x, y) => x + y
// console.log(sum(4, 5))
// import '../static/2-1'
// import '../static/reflect'
// import '../static/async_before'
// import '../static/Promise'
// import '../static/ajax_promise_success'
// import '../static/ajax_promise_all'
// import '../static/static_promise'
// import '../static/generator'
// import '../static/Iterator'
// import '../static/3-es7-array'
// import '../static/2-pow'
// import '../static/es8-async'
import '../static/es8-Object'